version: 1.2.0
environment:
  my_variable:
    secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA

image:
  - Visual Studio 2022
  - macOS
  - Ubuntu

jobs:
  - image: Visual Studio 2022
    build_script:
      - cmd: dotnet restore StrayCatRunner/StrayCatRunner.csproj
      - cmd: dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
      - cmd: dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish

  - image: macOS
    build_script:
      - dotnet restore StrayCatRunner/StrayCatRunner.csproj
      - dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
      - dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime osx-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish

  - image: Ubuntu
    build_script:
      - dotnet restore StrayCatRunner/StrayCatRunner.csproj
      - dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
      - dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime linux-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish

artifacts:
  - path: './publish/*'
    name: Executable

deploy:
  - provider: GitHub
    tag: release
    release: Release
    description: 'This is a test release, supporting Windows, macOS, and Linux.'
    auth_token:
      secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA
    artifact: Executable 
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: false