version: 1.2.3
environment:
  matrix:
    - IMAGE: 'Visual Studio 2022'
      RUNTIME: 'win-x64'
    - IMAGE: 'macOS'
      RUNTIME: 'osx-x64'
    - IMAGE: 'Ubuntu'
      RUNTIME: 'linux-x64'

  my_variable:
    secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA

# this is ugly but it works mabye

build_script:
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      Copy-Item -Path .\straycat_server.py -Destination ./publish
    )
  - if "%IMAGE%"=="Visual Studio 2022" (
      Compress-Archive -Path ./publish/* -DestinationPath ./publish/StrayCatRunner_Windows.zip
    )

  - if "%IMAGE%"=="macOS" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="macOS" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="macOS" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish/mac
    )
  - if "%IMAGE%"=="macOS" (
      Copy-Item -Path .\straycat_server.py -Destination ./publish/mac
    )
  - if "%IMAGE%"=="macOS" (
      Compress-Archive -Path ./publish/mac/* -DestinationPath ./publish/StrayCatRunner_Mac.zip
    )

  - if "%IMAGE%"=="Ubuntu" (
      dotnet restore StrayCatRunner/StrayCatRunner.csproj
    )
  - if "%IMAGE%"=="Ubuntu" (
      dotnet build StrayCatRunner/StrayCatRunner.csproj --configuration Release
    )
  - if "%IMAGE%"=="Ubuntu" (
      dotnet publish StrayCatRunner/StrayCatRunner.csproj --configuration Release --runtime %RUNTIME% /p:PublishSingleFile=true /p:PublishTrimmed=true /p:SelfContained=true --output ./publish/linux
    )
  - if "%IMAGE%"=="Ubuntu" (
      Copy-Item -Path .\straycat_server.py -Destination ./publish/linux
    )
  - if "%IMAGE%"=="Ubuntu" (
      Compress-Archive -Path ./publish/linux/* -DestinationPath ./publish/StrayCatRunner_Linux.zip
    )

artifacts:
  - path: './publish/*.zip'
    name: Archives


deploy:
  - provider: GitHub
    tag: release
    release: Release
    description: 'This is a test release, supporting Windows, macOS, and Linux.'
    auth_token:
      secure: C0IqVjv+wrTqiWI4cNlCXKndiCX+No8WMcWcsUlUW3ycgeZrjsyAocYEzLI1UTNA
    artifact: Executable 
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: false